### For reference, see `/opt/open5gs/etc/orig/open5gs/`
upf:
    pfcp:
    gtpu:
    subnet:
      - addr: 10.45.0.1/16
        dnn: internet
      #- addr: cafe::1/64
smf:
    pfcp:
      - name: smf
parameter:
max:
pool: